"""remove unique title

Revision ID: 9f47361ec6a3
Revises: f4d140f9448c
Create Date: 2018-11-23 17:39:46.350751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f47361ec6a3'
down_revision = 'f4d140f9448c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_feature_request_title', table_name='feature_request')
    op.create_index(op.f('ix_feature_request_title'), 'feature_request', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_feature_request_title'), table_name='feature_request')
    op.create_index('ix_feature_request_title', 'feature_request', ['title'], unique=1)
    # ### end Alembic commands ###
